#!/bin/bash
# Builds Inferno.ipa: compiles the SwiftUI front-end, bundles the emulator
# dylib, ad-hoc signs everything and zips it into an installable payload.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
BUILD="$ROOT/.build"
# Ищем библиотеку эмулятора там, где она обычно и лежит: сначала рядом с
# репозиторием, как описано в README, потом в дереве сборки. Переопределяется
# переменной INFERNO_DYLIB.
DYLIB="${INFERNO_DYLIB:-}"
if [ -z "$DYLIB" ]; then
    for candidate in \
        "$ROOT/../build/inferno/libqemu-aarch64-softmmu.dylib" \
        "$HOME/inferno-ios/build/inferno/libqemu-aarch64-softmmu.dylib"
    do
        [ -f "$candidate" ] && DYLIB="$candidate" && break
    done
fi
APP="$BUILD/Payload/Inferno.app"
SDK="$(xcrun --sdk iphoneos --show-sdk-path)"
TARGET="arm64-apple-ios16.0"

[ -n "$DYLIB" ] && [ -f "$DYLIB" ] || {
    echo "Нет библиотеки эмулятора. Соберите её или укажите INFERNO_DYLIB=" >&2
    exit 1
}

rm -rf "$BUILD"
mkdir -p "$APP/Frameworks"

echo "==> Компиляция"
# A stamp in the log removes any doubt about which build is actually running.
STAMP="$(date '+%Y-%m-%d %H:%M:%S')"
cat > "$ROOT/Sources/BuildInfo.swift" <<EOF
// Generated by build.sh — do not edit.
enum BuildInfo {
    static let stamp = "$STAMP"
}
EOF
xcrun --sdk iphoneos swiftc \
    -target "$TARGET" \
    -sdk "$SDK" \
    -O -wmo \
    -parse-as-library \
    -o "$APP/Inferno" \
    "$ROOT"/Sources/*.swift

echo "==> Сборка бандла"
cp "$ROOT/Resources/Info.plist" "$APP/Info.plist"
cp "$DYLIB" "$APP/Frameworks/"
chmod +x "$APP/Inferno"

# QEMU's data directory. Inferno drops the keymaps from its tree, but the VNC
# server still refuses to start without them, so take them from a stock QEMU.
KEYMAPS="${INFERNO_KEYMAPS:-/opt/homebrew/share/qemu/keymaps}"
[ -d "$KEYMAPS" ] || { echo "Нет keymap-файлов: $KEYMAPS" >&2; exit 1; }
mkdir -p "$APP/qemu-data"
cp -R "$KEYMAPS" "$APP/qemu-data/keymaps"

# No boot splash. Inferno's splash artwork belongs to ChefKiss and may not be
# shipped in derivative builds (ui/icons/CKBrandingNotice.md in the emulator
# tree); the fork starts without it.

# App icon. Icon Composer's .icon bundle is what actool takes now: it renders
# the layers into Assets.car for iOS 26's glass treatment and drops flat PNGs
# beside it for everything older. The Info.plist keys it needs come back in a
# partial plist, which is merged rather than transcribed — that way a change in
# the icon does not need a change here.
ICON="$ROOT/Resources/Inferno.icon"
if [ -d "$ICON" ]; then
    echo "==> Иконка"
    xcrun actool --compile "$APP" \
        --platform iphoneos \
        --minimum-deployment-target 16.0 \
        --app-icon Inferno \
        --output-partial-info-plist "$BUILD/icon.plist" \
        --include-all-app-icons \
        "$ICON" > /dev/null
    python3 - "$APP/Info.plist" "$BUILD/icon.plist" <<'PY'
import plistlib, sys
target, partial = sys.argv[1], sys.argv[2]
with open(target, 'rb') as f: info = plistlib.load(f)
with open(partial, 'rb') as f: extra = plistlib.load(f)
extra.pop('com.apple.actool.compilation-results', None)
info.update(extra)
with open(target, 'wb') as f: plistlib.dump(info, f)
PY
fi

echo "==> Подпись"
# The dylib is signed first: the app's seal covers it.
codesign --force --sign - --timestamp=none "$APP/Frameworks/$(basename "$DYLIB")"
codesign --force --sign - --timestamp=none \
    --entitlements "$ROOT/Resources/entitlements.plist" \
    "$APP"

echo "==> Упаковка"
cd "$BUILD"
# zip adds to an existing archive instead of replacing it, which would carry
# files from an earlier build into this one.
rm -f "$ROOT/Inferno.ipa"
zip -qry "$ROOT/Inferno.ipa" Payload -x '*.DS_Store'

echo
echo "Готово: $ROOT/Inferno.ipa"
ls -lh "$ROOT/Inferno.ipa"
