#!/bin/bash
# Builds Inferno.ipa: compiles the SwiftUI front-end, bundles the emulator
# dylib, ad-hoc signs everything and zips it into an installable payload.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
BUILD="$ROOT/.build"
# Ищем библиотеку эмулятора там, где она обычно и лежит: сначала рядом с
# репозиторием, как описано в README, потом в дереве сборки. Переопределяется
# переменной INFERNO_DYLIB.
DYLIB="${INFERNO_DYLIB:-}"
if [ -z "$DYLIB" ]; then
    for candidate in \
        "$ROOT/../build/inferno/libqemu-aarch64-softmmu.dylib" \
        "$HOME/inferno-ios/build/inferno/libqemu-aarch64-softmmu.dylib"
    do
        [ -f "$candidate" ] && DYLIB="$candidate" && break
    done
fi
APP="$BUILD/Payload/Inferno.app"
SDK="$(xcrun --sdk iphoneos --show-sdk-path)"
TARGET="arm64-apple-ios16.0"

[ -n "$DYLIB" ] && [ -f "$DYLIB" ] || {
    echo "Нет библиотеки эмулятора. Соберите её или укажите INFERNO_DYLIB=" >&2
    exit 1
}

rm -rf "$BUILD"
mkdir -p "$APP/Frameworks"

echo "==> Компиляция"
# A stamp in the log removes any doubt about which build is actually running.
STAMP="$(date '+%Y-%m-%d %H:%M:%S')"
cat > "$ROOT/Sources/BuildInfo.swift" <<EOF
// Generated by build.sh — do not edit.
enum BuildInfo {
    static let stamp = "$STAMP"
}
EOF
xcrun --sdk iphoneos swiftc \
    -target "$TARGET" \
    -sdk "$SDK" \
    -O -wmo \
    -parse-as-library \
    -o "$APP/Inferno" \
    "$ROOT"/Sources/*.swift

echo "==> Сборка бандла"
cp "$ROOT/Resources/Info.plist" "$APP/Info.plist"
cp "$DYLIB" "$APP/Frameworks/"
chmod +x "$APP/Inferno"

# QEMU's data directory. Inferno drops the keymaps from its tree, but the VNC
# server still refuses to start without them, so take them from a stock QEMU.
KEYMAPS="${INFERNO_KEYMAPS:-/opt/homebrew/share/qemu/keymaps}"
[ -d "$KEYMAPS" ] || { echo "Нет keymap-файлов: $KEYMAPS" >&2; exit 1; }
mkdir -p "$APP/qemu-data"
cp -R "$KEYMAPS" "$APP/qemu-data/keymaps"

# No boot splash. Inferno's splash artwork belongs to ChefKiss and may not be
# shipped in derivative builds (ui/icons/CKBrandingNotice.md in the emulator
# tree); the fork starts without it.

# App icon. Two sources, same actool-compile-then-merge-partial-plist dance:
# the Info.plist keys actool wants come back in a partial plist, merged
# rather than transcribed so a change to the icon needs no change here.
#
#   Inferno.icon   — Icon Composer's bundle, iOS 26's Liquid Glass layers.
#                    Only actool from Xcode 26+ can compile it.
#   Assets.xcassets — a flat PNG catalog rendered from the same artwork
#                    (scripts/render-icon.py), for older Xcode. Works
#                    everywhere but does not get the glass treatment.
#
# Local builds get the real one; INFERNO_NO_ICON=1 skips both (app ships
# with no icon at all).
compile_icon() { # compile_icon <catalog-dir> <app-icon-name>
    xcrun actool --compile "$APP" \
        --platform iphoneos \
        --minimum-deployment-target 16.0 \
        --app-icon "$2" \
        --output-partial-info-plist "$BUILD/icon.plist" \
        --include-all-app-icons \
        "$1" > /dev/null
    python3 - "$APP/Info.plist" "$BUILD/icon.plist" <<'PY'
import plistlib, sys
target, partial = sys.argv[1], sys.argv[2]
with open(target, 'rb') as f: info = plistlib.load(f)
with open(partial, 'rb') as f: extra = plistlib.load(f)
extra.pop('com.apple.actool.compilation-results', None)
info.update(extra)
with open(target, 'wb') as f: plistlib.dump(info, f)
PY
}

ICON="$ROOT/Resources/Inferno.icon"
FALLBACK_ICON="$ROOT/Resources/Assets.xcassets"
if [ -z "${INFERNO_NO_ICON:-}" ]; then
    if [ -d "$ICON" ] && xcrun actool --version >/dev/null 2>&1 && \
       xcrun actool --compile /tmp --app-icon Inferno "$ICON" >/tmp/actool-probe.log 2>&1; then
        echo "==> Иконка (Icon Composer)"
        compile_icon "$ICON" Inferno
    elif [ -d "$FALLBACK_ICON" ]; then
        echo "==> Иконка (плоский .xcassets — Xcode тут старше 26, .icon не берёт)"
        compile_icon "$FALLBACK_ICON" AppIcon
    fi
fi

echo "==> Помощник для гостя (nsio)"
# Читать и писать namespace NVMe внутри гостя может только бинарник с правами:
# шеллу блочные устройства закрыты. Помощник едет в бандле, приложение кладёт
# его в гостя один раз. Без него установка .ipa не ломается — она просто идёт по
# сети, которая в разы медленнее.
if [ -z "${INFERNO_NO_NSIO:-}" ] && command -v ldid >/dev/null 2>&1; then
    mkdir -p "$APP/guest-tools"
    "$ROOT/../netlab/build-nsio.sh" "$APP/guest-tools/nsio" >/dev/null
else
    echo "    нет ldid — собираю без помощника (быстрый канал будет недоступен)"
fi

echo "==> Подпись"
# The dylib is signed first: the app's seal covers it.
codesign --force --sign - --timestamp=none "$APP/Frameworks/$(basename "$DYLIB")"
codesign --force --sign - --timestamp=none \
    --entitlements "$ROOT/Resources/entitlements.plist" \
    "$APP"

echo "==> Упаковка"
cd "$BUILD"
# zip adds to an existing archive instead of replacing it, which would carry
# files from an earlier build into this one.
rm -f "$ROOT/Inferno.ipa"
zip -qry "$ROOT/Inferno.ipa" Payload -x '*.DS_Store'

echo
echo "Готово: $ROOT/Inferno.ipa"
ls -lh "$ROOT/Inferno.ipa"
